name = "IMUDevNNArchitectures"
uuid = "f70ee525-ba1a-4335-97e8-1e95512d282a"
authors = ["Marcin Mider <marcin.mider@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Lux = "0.5"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
